01.Fundamentals/11.BasicWebProject/Skeleton/ParkingSystem/Controllers/CarController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ModelBinding;
using ParkingSystem.Data;
using ParkingSystem.Data.Models;

namespace ParkingSystem.Controllers
{
    public class CarController : Controller
    {
        [HttpPost]
        public IActionResult Add(Car car)
        {
            if (DataAccess.Cars.Count == 4)
            {
                TempData["ErrorMessage"] = "Only space for 4 cars in the lot!";
            }
            else if(ModelState.IsValid && DataAccess.Cars.FirstOrDefault(x => x.PlateNumber == car.PlateNumber) == null)
            {
                DataAccess.Cars.Add(car);
            } 
            else
            {
                TempData["ErrorMessage"] = "Car already in the lot or the input was invalid!";
            }

            return Redirect("/");
        }

        [HttpPost]
        public IActionResult Delete(string plateNumber)
        {
            var car = DataAccess.Cars.FirstOrDefault(car => car.PlateNumber == plateNumber);
            DataAccess.Cars.Remove(car!);
            
            return Redirect("/");
        }
    }
}

01.Fundamentals/11.BasicWebProject/Skeleton/ParkingSystem/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using ParkingSystem.Data;

namespace ParkingSystem.Controllers
{
    public class HomeController : Controller
    {
        [HttpGet]
        public IActionResult Index()
        {
            return View(DataAccess.Cars);
        }
    }
}

01.Fundamentals/11.BasicWebProject/Skeleton/ParkingSystem/Views/Home/Index.cshtml
@model List<Car>
@{
    ViewData["Title"] = "Parking System";
    var errorMessage = TempData["ErrorMessage"] as string;
}

<header class="text-center">
    <h1 class="display-7">Parking system</h1>
</header>
<content>
    <table class="cars-table">
        <thead>
            <tr>
                <th class="col">MAKE</th>
                <th class="col">MODEL</th>
                <th class="col" id="plate-number-col">PLATE NUMBER</th>
                <th class="col"></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr class="car-data">
                    <td>
                        @Html.DisplayFor(modelItem => item.Make)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Model)
                    </td>
                    <td id ="plate-number">
                        <b>@Html.DisplayFor(modelItem => item.PlateNumber)</b>
                    </td>
                    <td>
                        <form id="delete-button" method="post" asp-controller="Car" asp-action="Delete">
                            <input type="hidden" name="plateNumber" asp-for="@item.PlateNumber" />
                            <input type="submit" value="Delete" class="btn btn-danger"/>
                        </form>
                    </td>
                </tr>
            }
        </tbody>
    </table>

    @using (Html.BeginForm("Add", "Car", FormMethod.Post, new { @class = "form-horizontal" }))
    {
        <div class="newCar-form">
            <div class="form-group">
                <label for="name" class="col-lg-2 control-label">Make</label>
                <div class="col-lg-10">
                    <input type="text" autofocus="autofocus" name="make" title="Make" class="form-control" id="name" />
                </div>
            </div>
            <div class="form-group">
                <label for="number" class="col-lg-2 control-label">Model</label>
                <div class="col-lg-10">
                    <input type="text" autofocus="autofocus" name="model" title="Model" class="form-control" id="name" />
                </div>
            </div>
            <div class="form-group">
                <label for="number" class="col-lg-2 control-label">Plate #</label>
                <div class="col-lg-10">
                    <input type="text" autofocus="autofocus" name="plateNumber" title="PlateNumber" class="form-control" id="number" />
                </div>
            </div>
            @if (!string.IsNullOrEmpty(errorMessage))
            {
                <div class="alert alert-danger" role="alert">
                    @errorMessage
                </div>
            }
            <div class="form-group" style="width: 30%">
                <div class="col-lg-10 mt-2 col-lg-offset-2">
                    <button type="submit" class="btn btn-success">Add</button>
                </div>
            </div>
        </div>
    }
</content>

01.Fundamentals/11.BasicWebProject/Skeleton/ParkingSystem/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ParkingSystem</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ParkingSystem.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm border-bottom box-shadow mb-3" style="background-color: #022E1E;">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index" style="color:white; ">ParkingSystem</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; @DateTime.Now.Year - ParkingSystem
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>