01.Fundamentals/11.BasicWebProject/SliDo/SliDo/SliDo/Models/ErrorViewModel.cs
namespace SliDo.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

01.Fundamentals/11.BasicWebProject/SliDo/SliDo/SliDo/Models/Home/IndexViewModel.cs
namespace SliDo.Models.Home
{
    public class IndexViewModel
    {
        public int Id { get; set; }
        public string Author { get; set; }
        public string Text { get; set; }

        public IndexViewModel() { }
        public IndexViewModel(int id, string author, string text) 
        {
            this.Id = id;
            this.Author = author;
            this.Text = text;
        }
    }
}

01.Fundamentals/11.BasicWebProject/SliDo/SliDo/SliDo/Models/Questions/CreateQuestionRequest.cs
namespace SliDo.Models.Questions
{
    public class CreateQuestionRequest
    {
        public string? Author { get; set; }
        public string Text { get; set; }
    }
}

01.Fundamentals/11.BasicWebProject/SliDo/SliDo/SliDo/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using SliDo.Data;
using SliDo.Models;
using SliDo.Models.Home;
using System.Diagnostics;

namespace SliDo.Controllers
{
    public class HomeController : Controller
    {
        private readonly ApplicationDbContext _dbContext;
        
        public HomeController(ApplicationDbContext dbContext)
        {
            this._dbContext = dbContext;
        }

        public IActionResult Index()
        {
            var questions = this._dbContext.Questions.Where(x => !x.IsAnswered)
                .OrderBy(x => x.Created)
                .Select(x => new IndexViewModel(x.Id, x.Author, x.Text))
                .ToList();

            return View(questions);
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

01.Fundamentals/11.BasicWebProject/SliDo/SliDo/SliDo/Controllers/QuestionsController.cs
using Microsoft.AspNetCore.Mvc;
using SliDo.Data;
using SliDo.Data.Migrations;
using SliDo.Models.Questions;

namespace SliDo.Controllers
{
    public class QuestionsController : Controller
    {
        private readonly ApplicationDbContext _dbContext;

        public QuestionsController(ApplicationDbContext dbContext)
        {
            this._dbContext = dbContext;
        }

        public IActionResult Create()
        {
            return View();
        }

        public IActionResult Delete(int id)
        {
            var question = _dbContext.Questions.FirstOrDefault(x => x.Id == id);
            question.IsAnswered = true;

            _dbContext.SaveChanges();

            return RedirectToAction("Index", "Home");
        }
        
        [HttpPost]
        public IActionResult Create(CreateQuestionRequest request)
        {
            if (!ModelState.IsValid)
            {
                return View(request);
            }

            this._dbContext.Questions.Add(new Question(request.Author, request.Text));
            this._dbContext.SaveChanges();

            return RedirectToAction("Index", "Home");
        }
    }
}

01.Fundamentals/11.BasicWebProject/SliDo/SliDo/SliDo/Views/Home/Index.cshtml
@using SliDo.Models.Home

@model List<IndexViewModel>
@{
    ViewData["Title"] = "Home Page";
}

<div>
    @foreach (var question in Model)
    {
        <div class="card mt-3">
            <div class="card-body">
                <h5 class="card-title">@question.Author</h5>
                <p class="card-text">@question.Text</p>
                @if (this.User.Identity.IsAuthenticated)
                {
                    <a type="submit" class="btn btn-outline-primary" asp-area="" asp-controller="Questions" asp-action="Delete" asp-route-id="@question.Id">Mark as answered</a>
                }
            </div>
        </div>
    }
</div>

01.Fundamentals/11.BasicWebProject/SliDo/SliDo/SliDo/Views/Questions/Create.cshtml
@using SliDo.Models.Questions
@model CreateQuestionRequest


@* <form asp-action="Create">
    <div class="form-group">
        <label asp-for="Text" class="col-sm-3 control-label">Text</label>
        <input asp-for="Text" class="form-control" placeholder="Enter your question here."/>
    </div>
    <div class="form-group">
        <label asp-for="Author" class="col-sm-3 control-label">Author</label>
        <input asp-for="Author" class="form-control" placeholder="Enter your name if you want or you will remain anonymous." />
    </div>
    <button type="submit" class="btn btn-secondary">Submit</button>
</form> *@

@using (Html.BeginForm("Create","Questions",FormMethod.Post)) {
    @Html.EditorForModel()
    <input type="submit" value="Ask question" />
}

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

01.Fundamentals/11.BasicWebProject/SliDo/SliDo/SliDo/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SliDo</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/SliDo.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">SliDo</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Questions" asp-action="Create">Ask Question</a>
                        </li>
                    </ul>
                    @* <partial name="_LoginPartial" /> *@
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - SliDo - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>